"""Validation for plans generated by the Planned Agent."""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from common.py_schemas import Plan
from tools import tool_registry as registry


DETERMINISTIC_AGGREGATE_TOOL = "graphrag__deterministic_aggregate"

RETRIEVAL_TOOLS = {
    "graphrag__structural_retrieve",
    "graphrag__hybrid_search",
    "graphrag__similarity_search",
    "graphrag__contextual_search",
    "graphrag__community_search",
}

AGGREGATION_PATTERNS = [
    r"\bhow many\b",
    r"\bnumber of\b",
    r"\bcount\b",
    r"\btotal number\b",
    r"\bmore than\b",
    r"\bless than\b",
    r"\bat least\b",
    r"\bat most\b",
    r"\baverage\b",
    r"\bmean\b",
    r"\bsum of\b",
    r"\bmost\b",
    r"\bleast\b",
    r"\bmaximum\b",
    r"\bminimum\b",
    r"\bhighest\b",
    r"\blowest\b",
]


class PlanValidationError(ValueError):
    """Raised when the planner creates an unsafe or unusable plan."""

    def __init__(self, errors: list[str]):
        self.errors = errors
        super().__init__("; ".join(errors))


@dataclass
class PlanValidationResult:
    valid: bool
    errors: list[str] = field(default_factory=list)


def _is_aggregation_question(question: str) -> bool:
    return any(
        re.search(pattern, question, flags=re.IGNORECASE)
        for pattern in AGGREGATION_PATTERNS
    )


def _has_dependency_cycle(
    dependency_map: dict[str, list[str]],
) -> bool:
    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(step_id: str) -> bool:
        if step_id in visiting:
            return True

        if step_id in visited:
            return False

        visiting.add(step_id)

        for dependency in dependency_map.get(step_id, []):
            if dependency in dependency_map and visit(dependency):
                return True

        visiting.remove(step_id)
        visited.add(step_id)
        return False

    return any(visit(step_id) for step_id in dependency_map)


def validate_plan(
    plan: Plan,
    question: str,
    ctx=None,
) -> PlanValidationResult:
    """Validate a Planned-Agent DAG before any tool is executed."""

    errors: list[str] = []
    steps = list(plan.steps or [])

    if not steps:
        return PlanValidationResult(
            valid=False,
            errors=["The planner returned no steps."],
        )

    step_ids = [step.id for step in steps]

    if any(not step_id or not step_id.strip() for step_id in step_ids):
        errors.append("Every plan step must have a non-empty ID.")

    duplicate_ids = sorted(
        {
            step_id
            for step_id in step_ids
            if step_ids.count(step_id) > 1
        }
    )

    if duplicate_ids:
        errors.append(
            "Duplicate step IDs: " + ", ".join(duplicate_ids)
        )

    known_tools = set(registry.tool_names(ctx))
    answer_steps = []
    tool_steps = []

    for step in steps:
        if step.kind == "answer":
            answer_steps.append(step)

            if step.tool:
                errors.append(
                    f"Answer step '{step.id}' must have an empty tool."
                )
        else:
            tool_steps.append(step)

            if not step.tool:
                errors.append(
                    f"Tool step '{step.id}' has an empty tool name."
                )
            elif step.tool not in known_tools:
                errors.append(
                    f"Step '{step.id}' references unknown tool "
                    f"'{step.tool}'."
                )

        for dependency in step.depends_on or []:
            if dependency not in step_ids:
                errors.append(
                    f"Step '{step.id}' depends on missing step "
                    f"'{dependency}'."
                )

            if dependency == step.id:
                errors.append(
                    f"Step '{step.id}' depends on itself."
                )

        for argument_name, reference in (
            step.arg_bindings or {}
        ).items():
            source_step_id = reference.split(".", 1)[0]

            if source_step_id not in step_ids:
                errors.append(
                    f"Binding '{argument_name}' in step '{step.id}' "
                    f"references missing step '{source_step_id}'."
                )

            if source_step_id not in (step.depends_on or []):
                errors.append(
                    f"Binding '{argument_name}' in step '{step.id}' "
                    f"references '{source_step_id}', but that step is "
                    "not declared in depends_on."
                )

    if not answer_steps:
        errors.append("The plan has no final answer step.")

    if len(answer_steps) > 1:
        errors.append("The plan contains multiple answer steps.")

    if not tool_steps:
        errors.append(
            "The plan is answer-only and contains no retrieval or "
            "evidence-producing tool."
        )

    retrieval_steps = [
        step
        for step in tool_steps
        if step.tool in RETRIEVAL_TOOLS
    ]

    if not retrieval_steps:
        errors.append(
            "The plan contains no supported retrieval step."
        )

    if answer_steps and tool_steps:
        answer_dependencies = set(
            answer_steps[0].depends_on or []
        )

        if not answer_dependencies:
            errors.append(
                "The answer step does not depend on any evidence step."
            )

        tool_ids = {step.id for step in tool_steps}

        if not answer_dependencies.intersection(tool_ids):
            errors.append(
                "The answer step is not connected to a tool result."
            )

    if _is_aggregation_question(question):
        aggregate_steps = [
            step
            for step in tool_steps
            if step.tool == DETERMINISTIC_AGGREGATE_TOOL
        ]

        if not aggregate_steps:
            errors.append(
                "Aggregation question requires "
                "graphrag__deterministic_aggregate."
            )
        else:
            aggregate_step = aggregate_steps[0]

            if not aggregate_step.depends_on:
                errors.append(
                    "The deterministic aggregation step must depend "
                    "on a retrieval step."
                )

            has_document_ids = (
                "document_ids" in (aggregate_step.args or {})
                or "document_ids"
                in (aggregate_step.arg_bindings or {})
            )

            if not has_document_ids:
                errors.append(
                    "The deterministic aggregation step requires "
                    "document_ids through args or arg_bindings."
                )

    dependency_map = {
        step.id: list(step.depends_on or [])
        for step in steps
    }

    if _has_dependency_cycle(dependency_map):
        errors.append("The plan contains a dependency cycle.")

    return PlanValidationResult(
        valid=not errors,
        errors=errors,
    )


def require_valid_plan(
    plan: Plan,
    question: str,
    ctx=None,
) -> Plan:
    """Return the plan when valid; otherwise raise a specific error."""

    result = validate_plan(
        plan=plan,
        question=question,
        ctx=ctx,
    )

    if not result.valid:
        raise PlanValidationError(result.errors)

    return plan
